// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-3UoyFOe9WmxEw6ayw8D5i-XOhgeglqY',
    appId: '1:840500555168:web:12824668c8025f73cd08c5',
    messagingSenderId: '840500555168',
    projectId: 'raspberry-376ef',
    authDomain: 'raspberry-376ef.firebaseapp.com',
    storageBucket: 'raspberry-376ef.appspot.com',
    measurementId: 'G-F0PL4BR7DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP2ptCqxLX6_SdBSURy6m2nAPtdlv5yDs',
    appId: '1:840500555168:android:33f3a21637030144cd08c5',
    messagingSenderId: '840500555168',
    projectId: 'raspberry-376ef',
    storageBucket: 'raspberry-376ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkSlwaqIO5xY31eX-S_5C3qvbeWdMENok',
    appId: '1:840500555168:ios:2997d3f26ac57cf1cd08c5',
    messagingSenderId: '840500555168',
    projectId: 'raspberry-376ef',
    storageBucket: 'raspberry-376ef.appspot.com',
    iosBundleId: 'com.example.raspberrypiwithfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkSlwaqIO5xY31eX-S_5C3qvbeWdMENok',
    appId: '1:840500555168:ios:2997d3f26ac57cf1cd08c5',
    messagingSenderId: '840500555168',
    projectId: 'raspberry-376ef',
    storageBucket: 'raspberry-376ef.appspot.com',
    iosBundleId: 'com.example.raspberrypiwithfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-3UoyFOe9WmxEw6ayw8D5i-XOhgeglqY',
    appId: '1:840500555168:web:4fc6479778e17e95cd08c5',
    messagingSenderId: '840500555168',
    projectId: 'raspberry-376ef',
    authDomain: 'raspberry-376ef.firebaseapp.com',
    storageBucket: 'raspberry-376ef.appspot.com',
    measurementId: 'G-1KZE9FNW8Y',
  );

}